### ISSUE TITLE
pdfetch_EUROSTAT() not finding available series

### ISSUE THREAD

**Issue by EconGeo** [abielr/pdfetch#1]
I am having an issue with pdfetch_EUROSTAT function.  It does not seem to work for any dataset except the one given in the documentation usage example.  For example, I am attempting to download the volume index for GDP.  The function
`pdfetch_EUROSTAT_DSD('namq_gdp_k')` returns the full list of dimensions to the data cube, yet when I attempt to download the data with:
    `gdp_pch <-   pdfetch_EUROSTAT('namq_gdp_k',FREQ='Q',S_ADJ='NSA',UNIT='PCH_SAME',INDIC_NA='B1GM',GEO='BE')`
 I get 
    `Warning message:
    In pdfetch_EUROSTAT("namq_gdp_k") : No series found`
even though I have verified that the series exists and is available on the website.  I have tried adding all and deleting all dimensions of the data cube and the error still exists.  Is this function only available for the 'namq_gdp_c' dataset?

**Comment by abielr** [comment]
My apologies, the code on Github got out of sync with the latest version on CRAN. I've just released a new version, 0.1.6, which is posted to Github and will be on CRAN presently. I was able to run your code example successfully. Let me know if you continue to experience problems.

**Comment by EconGeo** [comment]
Thank you and thank you for creating such a great package.  I will let you know if there are any further issues and glad I could call attention to CRAN - github sync issue.  You are a gentleman and a scholar.
