### ISSUE TITLE
Issue with pdfetch_YAHOO 

### ISSUE THREAD

**Issue by Jaraya08** [abielr/pdfetch#13]
I am getting an error when I try to run pdfetch_YAHOO it seems that the GET URL is wrong in the code.

**Error getting**
![image](https://github.com/abielr/pdfetch/assets/43132386/23b423a8-93fb-4a57-a3e7-e1fad2edbde5)

**The error may be caused by the URL making the query**
![image](https://github.com/abielr/pdfetch/assets/43132386/73bd3c3f-2b70-4751-ae1a-183970d8b6c2)

**Yahoo query link**
![image](https://github.com/abielr/pdfetch/assets/43132386/a151b3fa-b53e-4c6c-acd2-ac554b5ae1b1)

Would you be so kind to verify this bug please =).

**Comment by ClimberMel** [comment]
I believe the &crumb is unnecessary.  This `https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=1577836800&period2=1684454400&interval=1d&events=history` works to retrieve a csv of data.

**Comment by abielr** [comment]
This is fixed in v0.2.9, which has just been posted on Github. CRAN is on summer holiday and is not accepting submissions until August 8, I will post it on CRAN as soon as they are ready again.
