### ISSUE TITLE
Curl Malformed URL

### ISSUE THREAD

**Issue by jzadra** [abielr/pdfetch#14]
pdfetch_YAHOO("MSFT")

Error in curl::curl_fetch_memory(url, handle = h$ch) : 
  URL rejected: Malformed input to a URL function

**Comment by ecakan** [comment]
I have the same issue. Why is it not working anymore? It used to work!

**Comment by abielr** [comment]
Version 0.2.9 which fixes this has just been submitted to CRAN and will be available soon
