### ISSUE TITLE
pdfetch_FRED no longer working?

### ISSUE THREAD

**Issue by sjdres** [abielr/pdfetch#17]
I've been using pdfetch_FRED without issue for months. Recently I've been receiving the following:

> pdfetch_FRED(c("GDPC1", "PCECC96"))
Error in textConnection(content(req, encoding = "utf-8")) : 
  invalid 'text' argument

Everything is up to date, and I've successfully accessed data using pdfetch for other sources.

**Comment by abielr** [comment]
@sjdres - I just fixed the issue with v0.3.0. This version is on Github and has been sent to CRAN where it will appear shortly.
