### ISSUE TITLE
pdfetch_WB no longer works

### ISSUE THREAD

**Issue by tayroc122** [abielr/pdfetch#18]
pdfetch_WB now pulls this error:

![image](https://github.com/user-attachments/assets/f18fd901-1bd3-41fe-a05f-a4e5ea6c5bfc)

I've run the same script several times before and never had the error. Nothing in the script has changed. It must have been an update that broke it. Please advise.

**Comment by abielr** [comment]
Issue fixed with v0.3.1, which will be on CRAN shortly.
