### ISSUE TITLE
pdfetch_yahoo stopped working

### ISSUE THREAD

**Issue by ArthurSinko** [abielr/pdfetch#19]
Example: the code from the help file does not work any more.

library(pdfetch)

pdfetch_YAHOO(c("^gspc","^ixic"))

NULL

Warning messages:
1: In pdfetch_YAHOO(c("^gspc", "^ixic")) : Could not find series '^gspc'
2: In pdfetch_YAHOO(c("^gspc", "^ixic")) : Could not find series '^ixic'

The same is true for any other ticker:

pdfetch_YAHOO("INTC")

NULL
Warning message:
In pdfetch_YAHOO("INTC") : Could not find series 'INTC'

**Comment by abielr** [comment]
Fixed in v0.3.2, now on CRAN
