### ISSUE TITLE
pdfetch_FRED stopped working

### ISSUE THREAD

**Issue by GTuley** [abielr/pdfetch#21]
I have been using this code for the past few weeks without any issues but now it has stopped retrieving the data from FRED. Have tried on other devices and IDEs (Rstudio, VScode) and ensured I have the most current updated version of R and the package.
`main_data <- pdfetch_FRED(c("IRLTLT01USQ156N", "HDTGPDUSQ163N", "IRLTLT01CAQ156N", "HDTGPDCAQ163N", "IRLTLT01DEQ156N", "IRLTLT01KRQ156N", "IRLTLT01AUQ156N", "HDTGPDAUQ163N", "HDTGPDDEQ163N", "HDTGPDKRQ163N"))` which returns the error `Error in df$DATE : $ operator is invalid for atomic vectors`

**Comment by abielr** [comment]
Fixed issue in v3.3 which has been posted to Github and should be on CRAN shortly.
