### ISSUE TITLE
ONS format change?

### ISSUE THREAD

**Issue by TimMurnaghan** [abielr/pdfetch#3]
pdfetch_ONS(c("LF24","LF2G"), "lms")
Error in 2:(which(fr[, 1] == "© Crown Copyright") - 1) : 
  argument of length 0

**Comment by abielr** [comment]
Thanks @TimMurnaghan, a new version of the package will be available shortly that fixes the problem.

**Comment by marekrojicek** [comment]
Hi, the pdfetch_ONS command doesn't work again - I think the ONS has changed their API: ["We are separating the API from the website. This is not a choice we have made by chance; we are looking to define consistent identifiers for our information and our previous JSON API (which will still exist) was mapped directly to our human readable URLs and was starting to cause some issues."](http://digitalblog.ons.gov.uk/2017/06/15/api/)

I would be really grateful if you could have a look into it! Thanks!

**Comment by abielr** [comment]
Issue resolved in version 0.2.2.
