### ISSUE TITLE
fetching volume from Yahoo

### ISSUE THREAD

**Issue by A5403895** [abielr/pdfetch#4]
I want to fetch historical stock prices from Yahoo finance with "pdfetch" package for a series of tickers,this is my code: 
`d1<-pdfetch_YAHOO(identifiers[1:636], c("high","low","close","volume"),from = as.Date("2016-01-01"), to = "2016-01-30")
`but I received this message: 
`Error in (function (..., all = TRUE, fill = NA, suffixes = NULL, join = "outer", : unsupported data type`
it is working, when I fetch the prices of high low and close.

**Comment by abielr** [comment]
Resolved in [v0.2.0](https://github.com/abielr/pdfetch/commit/7fe7b8e01574e4740b83fbb03506fd6999f2d1c4). Will be available on CRAN imminently.

**Comment by A5403895** [comment]
ok, thanks a lot.
